# Service: Nginx

ARG NGINX_VERSION=latest

FROM nginx:${NGINX_VERSION}

RUN apt-get update && apt-get install -y \
    nginx && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

CMD ["nginx", "-g", "daemon off;"]
