# Service: Apache

ARG APACHE_VERSION=latest

FROM httpd:${APACHE_VERSION}

RUN apt-get update && apt-get install -y \
    apache2 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Enable Apache mods
RUN a2enmod rewrite headers

WORKDIR /var/www/html

CMD ["httpd-foreground"]
